name: Build and Test Pull Request

# Trigger the workflow on push or pull request
on:
  push:
  pull_request:
    types: [opened, synchronize]

env:
  GOPROXY: https://proxy.golang.org/
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GO_VERSION: 1.19.0
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Build image
      env:
        TAG_LATEST: "false"
      run: |
        make multiarch-build
    - name: Upload image
      uses: actions/upload-artifact@v2
      with:
        name: image
        path: image/contour-*.tar
    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#contour-ci-notifications'
      if: ${{ failure() && github.ref == 'refs/heads/main' }}
  upgrade:
    runs-on: ubuntu-latest
    needs: [build-image]
    strategy:
      matrix:
        # use stable kubernetes_version values since they're included
        # in the name of the GitHub Actions job, and we don't want to
        # have to update branch protection rules every time we change
        # a Kubernetes version number.
        kubernetes_version: ["kubernetes:latest", "kubernetes:n-1", "kubernetes:n-2"]
        # include defines an additional variable (the specific node
        # image to use) for each kubernetes_version value.
        include:
          - kubernetes_version: "kubernetes:latest"
            node_image: "docker.io/kindest/node:v1.25.2@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace"
          - kubernetes_version: "kubernetes:n-1"
            node_image: "docker.io/kindest/node:v1.24.6@sha256:97e8d00bc37a7598a0b32d1fabd155a96355c49fa0d4d4790aab0f161bf31be1"
          - kubernetes_version: "kubernetes:n-2"
            node_image: "docker.io/kindest/node:v1.23.12@sha256:9402cf1330bbd3a0d097d2033fa489b2abe40d479cc5ef47d0b6a6960613148a"
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch history for all tags and branches so we can figure out most
          # recent release tag.
          fetch-depth: 0
      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image
          path: image
      - uses: actions/cache@v2
        with:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ github.job }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: add deps to path
        run: |
          ./hack/actions/install-kubernetes-toolchain.sh $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: upgrade tests
        env:
          NODEIMAGE: ${{ matrix.node_image }}
          MULTINODE_CLUSTER: "true"
          LOAD_PREBUILT_IMAGE: "true"
          CONTOUR_UPGRADE_FROM_VERSION: v1.22.1
        run: |
          export CONTOUR_E2E_IMAGE="ghcr.io/projectcontour/contour:$(ls ./image/contour-*.tar | sed -E 's/.*contour-(.*).tar/\1/')"
          make upgrade
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#contour-ci-notifications'
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
